site_name: MiSTer Companion — Stream Deck
site_url: https://hudsonbrendon.github.io/mister-companion-streamdeck/
repo_url: https://github.com/hudsonbrendon/mister-companion-streamdeck
theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
nav:
  - Home: index.md
  - Install: INSTALL.md
  - Usage: USAGE.md
  - Features: FEATURES.md
  - Development: DEVELOPMENT.md
  - Troubleshooting: TROUBLESHOOTING.md
